services:
  jqplay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jqplay
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@pg:5432/jqplay
      HOSTNAME: "0.0.0.0"
      PORT: 7500
    command: sh -c "prisma migrate dev && node server.js"
    ports:
      - "127.0.0.1:7500:7500"
    networks:
      - jq-network
      - bridge
    depends_on:
      pg:
        condition: service_healthy
    # restart: unless-stopped

  pg:
    image: postgres:16
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jqplay
    ports:
      - "5432:5432"
    networks:
      - jq-network
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jqplay"]
      interval: 2s
      retries: 5
      start_period: 10s
      timeout: 10s

networks:
  jq-network:
    internal: true
  bridge:
    driver: bridge
