# fly.toml app configuration file generated for jqplay-next on 2024-06-09T22:44:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jqplay-next'
primary_region = 'sea'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[deploy]
release_command = "npx prisma migrate deploy"

[[vm]]
size = 'shared-cpu-2x'
memory = '1gb'
