app = 'jqplay-next'
primary_region = 'sea'

[build]
dockerfile = "Dockerfile"

[deploy]
release_command = 'npx --yes prisma migrate deploy'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 2
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = 256

[[http_service.checks]]
grace_period = "3s"
interval = "30s"
timeout = "5s"
method = "GET"
path = "/api/health"
